import { AlertTriangle, CheckCircle, Info, XCircle } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

interface PredictionResultsProps {
  prediction: string;
  drugs: string[];
}

const PredictionResults = ({ prediction, drugs }: PredictionResultsProps) => {
  // Parse the prediction to extract severity if mentioned
  const getSeverityInfo = () => {
    const lowerPrediction = prediction.toLowerCase();
    
    if (lowerPrediction.includes("high risk") || lowerPrediction.includes("severe")) {
      return {
        level: "high",
        icon: XCircle,
        color: "text-destructive",
        bgColor: "bg-destructive/10",
        label: "High Risk"
      };
    } else if (lowerPrediction.includes("medium risk") || lowerPrediction.includes("moderate")) {
      return {
        level: "medium",
        icon: AlertTriangle,
        color: "text-warning",
        bgColor: "bg-warning/10",
        label: "Medium Risk"
      };
    } else if (lowerPrediction.includes("low risk") || lowerPrediction.includes("minimal")) {
      return {
        level: "low",
        icon: Info,
        color: "text-success",
        bgColor: "bg-success/10",
        label: "Low Risk"
      };
    }
    
    return {
      level: "unknown",
      icon: CheckCircle,
      color: "text-primary",
      bgColor: "bg-primary/10",
      label: "Analysis Complete"
    };
  };

  const severityInfo = getSeverityInfo();
  const SeverityIcon = severityInfo.icon;

  return (
    <Card className="shadow-medical animate-in fade-in duration-500">
      <CardHeader>
        <div className="flex items-start justify-between">
          <div>
            <CardTitle>Analysis Results</CardTitle>
            <CardDescription>
              Interaction analysis for {drugs.length} drugs
            </CardDescription>
          </div>
          <div className={`flex items-center gap-2 px-3 py-1.5 rounded-lg ${severityInfo.bgColor}`}>
            <SeverityIcon className={`w-4 h-4 ${severityInfo.color}`} />
            <span className={`text-sm font-semibold ${severityInfo.color}`}>
              {severityInfo.label}
            </span>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Drug List */}
        <div className="flex flex-wrap gap-2 pb-4 border-b border-border">
          {drugs.map((drug) => (
            <Badge key={drug} variant="secondary" className="text-sm">
              {drug}
            </Badge>
          ))}
        </div>

        {/* Prediction Content */}
        <div className="prose prose-sm max-w-none">
          <div className="bg-muted/50 rounded-lg p-4">
            <div className="whitespace-pre-wrap text-foreground leading-relaxed">
              {prediction}
            </div>
          </div>
        </div>

        {/* Disclaimer */}
        <div className="bg-accent/50 border border-accent-foreground/20 rounded-lg p-3 mt-4">
          <p className="text-xs text-accent-foreground/80">
            <strong>Important:</strong> This analysis is generated by AI and should be used as a supplementary 
            tool only. Always consult with a qualified healthcare professional before making any medical decisions. 
            The predictions are based on general pharmacological knowledge and may not account for individual 
            patient factors.
          </p>
        </div>
      </CardContent>
    </Card>
  );
};

export default PredictionResults;
